import {
  POINTS_15,
  POINTS_30,
  POINTS_40,
  POINTS_AD,
  POINTS_GAME,
  UNFORCED_FOREHAND_USER,
  UNFORCED_BACKHAND_USER,
  UNFORCED_FOREHAND_OPPONENT,
  UNFORCED_BACKHAND_OPPONENT,
  ACES_USER,
  DOUBLE_FAULTS_USER,
  ACES_OPPONENT,
  DOUBLE_FAULTS_OPPONENT,
  WINNERS_FOREHAND_USER,
  WINNERS_BACKHAND_USER,
  WINNERS_FOREHAND_OPPONENT,
  WINNERS_BACKHAND_OPPONENT,
  UNSPECIFIED_POINT_USER,
  UNSPECIFIED_POINT_OPPONENT,
} from "@/logic/types.js";

import { convertGamesToStats } from "@/logic/gamesToStats.js";

const testArray1 = [
  {
    activeReport: false,
    user: "GAME",
    opponent: "40",
    points: [
      "unforcedForehandOpponent",
      "unforcedForehandUser",
      "winnersForehandUser",
      "winnersForehandOpponent",
      "unforcedForehandOpponent",
      "unforcedForehandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "acesUser",
      "unspecifiedPointOpponent",
      "doubleFaultsOpponent",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointUser",
    ],
  },
  {
    activeReport: false,
    user: "GAME",
    opponent: "40",
    points: [
      "unforcedBackhandOpponent",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unforcedBackhandOpponent",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "doubleFaultsOpponent",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointUser",
    ],
  },
  {
    activeReport: false,
    user: "GAME",
    opponent: "40",
    points: [
      "winnersForehandUser",
      "winnersForehandOpponent",
      "unforcedForehandOpponent",
      "unforcedForehandUser",
      "unspecifiedPointUser",
      "winnersForehandOpponent",
      "unspecifiedPointUser",
      "unforcedForehandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "doubleFaultsOpponent",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointUser",
    ],
  },
  {
    activeReport: false,
    user: "GAME",
    opponent: "40",
    points: [
      "winnersBackhandUser",
      "winnersBackhandOpponent",
      "unforcedBackhandOpponent",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedBackhandUser",
      "doubleFaultsOpponent",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointUser",
    ],
  },
  {
    activeReport: false,
    user: "GAME",
    opponent: "40",
    points: [
      "unforcedForehandOpponent",
      "unforcedForehandUser",
      "unspecifiedPointUser",
      "winnersForehandOpponent",
      "unforcedForehandOpponent",
      "unforcedForehandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointUser",
    ],
  },
  {
    activeReport: false,
    user: "GAME",
    opponent: "40",
    points: [
      "unforcedBackhandOpponent",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unforcedBackhandOpponent",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "doubleFaultsUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointUser",
      "unspecifiedPointUser",
    ],
  },
  {
    activeReport: false,
    user: "40",
    opponent: "GAME",
    points: [
      "winnersForehandUser",
      "winnersForehandOpponent",
      "unforcedForehandOpponent",
      "unforcedForehandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedForehandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointOpponent",
    ],
  },
  {
    activeReport: false,
    user: "40",
    opponent: "GAME",
    points: [
      "winnersBackhandUser",
      "unspecifiedPointOpponent",
      "unforcedBackhandOpponent",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedBackhandUser",
      "doubleFaultsUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointOpponent",
    ],
  },
  {
    activeReport: false,
    user: "40",
    opponent: "GAME",
    points: [
      "unforcedForehandOpponent",
      "unforcedForehandUser",
      "unspecifiedPointUser",
      "winnersForehandOpponent",
      "unforcedForehandOpponent",
      "unforcedForehandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointOpponent",
    ],
  },
  {
    activeReport: false,
    user: "40",
    opponent: "GAME",
    points: [
      "unforcedBackhandOpponent",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "doubleFaultsUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointOpponent",
    ],
  },
];

const testObj1 = {
  numberOfGamesUser: 6,
  numberOfGamesOpponent: 4,
  unforcedForehandUser: 10,
  unforcedBackhandUser: 15,
  unforcedForehandOpponent: 8,
  unforcedBackhandOpponent: 7,
  acesUser: 1,
  doubleFaultsUser: 3,
  acesOpponent: 0,
  doubleFaultsOpponent: 4,
  winnersForehandUser: 3,
  winnersBackhandUser: 2,
  winnersForehandOpponent: 6,
  winnersBackhandOpponent: 1,
};

const testObj2 = {
  numberOfGamesUser: 1,
  numberOfGamesOpponent: 1,
  unforcedForehandUser: 10,
  unforcedBackhandUser: 15,
  unforcedForehandOpponent: 8,
  unforcedBackhandOpponent: 7,
  acesUser: 1,
  doubleFaultsUser: 3,
  acesOpponent: 0,
  doubleFaultsOpponent: 4,
  winnersForehandUser: 3,
  winnersBackhandUser: 2,
  winnersForehandOpponent: 6,
  winnersBackhandOpponent: 1,
};

const testArray2 = [
  {
    activeReport: false,
    user: "GAME",
    opponent: "40",
    points: [
      "unforcedForehandOpponent",
      "unforcedForehandUser",
      "winnersForehandUser",
      "winnersForehandOpponent",
      "unforcedForehandOpponent",
      "unforcedForehandUser",
      "winnersForehandUser",
      "winnersForehandOpponent",
      "unforcedForehandOpponent",
      "unforcedForehandUser",
      "winnersForehandUser",
      "winnersForehandOpponent",
      "unforcedForehandOpponent",
      "unforcedForehandUser",
      "unspecifiedPointUser",
      "winnersForehandOpponent",
      "unforcedForehandOpponent",
      "unforcedForehandUser",
      "unspecifiedPointUser",
      "winnersForehandOpponent",
      "unforcedForehandOpponent",
      "unforcedForehandUser",
      "unspecifiedPointUser",
      "winnersForehandOpponent",
      "unforcedForehandOpponent",
      "unforcedForehandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unforcedForehandOpponent",
      "unforcedForehandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedForehandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedForehandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "acesUser",
      "unspecifiedPointOpponent",
      "doubleFaultsOpponent",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "doubleFaultsOpponent",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "doubleFaultsOpponent",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "doubleFaultsOpponent",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointUser",
    ],
  },
  {
    activeReport: false,
    user: "40",
    opponent: "GAME",
    points: [
      "unforcedBackhandOpponent",
      "unforcedBackhandUser",
      "winnersBackhandUser",
      "winnersBackhandOpponent",
      "unforcedBackhandOpponent",
      "unforcedBackhandUser",
      "winnersBackhandUser",
      "unspecifiedPointOpponent",
      "unforcedBackhandOpponent",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unforcedBackhandOpponent",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unforcedBackhandOpponent",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unforcedBackhandOpponent",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unforcedBackhandOpponent",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedBackhandUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unforcedBackhandUser",
      "doubleFaultsUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "doubleFaultsUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "doubleFaultsUser",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointUser",
      "unspecifiedPointOpponent",
      "unspecifiedPointOpponent",
    ],
  },
];

test("games to stats 10 games", () => {
  const result = convertGamesToStats(testArray1);
  expect(result).toEqual(testObj1);
});

test("games to stats 2 games", () => {
  const result = convertGamesToStats(testArray2);
  expect(result).toEqual(testObj2);
});
